### ISSUE TITLE
design the activities tab

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#1]
Design an activity tab for the application in Figma as an initial design idea for the platform.

**Comment by panchi64** [comment]
The initial idea of this page was for it to contain the following information:

- An area for messaging (?)
- An area for notifications (?)
- Any other thing that could be useful in the app that can be constrained to "Activities".
  - If you do add something to it, put it on the ideas pool! Anything you can think of is viable 😄 

[Link to Figma page](https://www.figma.com/file/i4Tz0s1kqkIRI2JLh3KuKR/Main-App-Tabs---Designs?type=design&node-id=0%3A1&mode=design&t=kP3B1RwCZ2xYvWrV-1)

**Comment by PinkSylvie** [comment]
What are the scores for these tickets?

**Comment by panchi64** [comment]
> What are the scores for these tickets?

Thanks for asking, I was unaware that was our responsibility. Just spoke to the professor about it.

As soon as I get a chance I'll give it a score value. Considering it's nothing difficult nor directly urgent. It shouldn't be worth much imo.
