### ISSUE TITLE
Design Services page style using Figma

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#10]
Assignees will be tasked with creating a draft of how they think the corresponding page should look like

**Comment by OrdepA17** [comment]
The service page will contain a small icon that will lead to the user's profile, it will also contain an area where the user can access the different departments that the service will cover (Math, Physics, ect). This will drop down and reveal the classes within the each department (Precalculus, Calculus, ect) and then after selecting a class the user will see the available tutors with their names, degree and schedule ([Profile pictures or icons] Ordep Agustin ICOM MWF 12:00pm-1:00pm) 

The Figma project is located here: https://www.figma.com/file/EjTKhIoC3vWCSzQZHi7duD/TEAM-4---UI-Design-(Copy)?type=design&node-id=4213%3A1335&mode=design&t=wY21h0PsI7quo7ZN-1

**Comment by Jeisen515** [comment]
We finalized our initial sketch of the service page UI. I attached an image for further evaluation.
![ServicePageUI](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72313954/defa7735-510f-471a-9cb0-9b44eafa7e4b)

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams. 
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 4 Points (for team collaboration)

Total: 4 Points Awarded for each developer
