### ISSUE TITLE
TEAM 4 - Courses Query Documentation

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#100]
Document all queries created from Issue #89  in to the Database Documentation from Issue #87 
Attach results, query and a brief explanation into the documentation. Comment under this issue when task has been completed.

Task Worth: 20pts (10 pts Deadline is tomorrow!!! priority * 2pts Easy difficulty)

**Comment by DanielFebles** [comment]
Jadiell and I have finished this task.

**Comment by OrdepA17** [comment]
Good work! Points have been updated.
