### ISSUE TITLE
TEAM 4 - API Integration Documentaion

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#101]
In this task, you will create the documentation of the work done on Issue #40 and you will add it to the Database documentation file found in Issue #87. Add a brief explanation of the integration and include a link to the branch where it was worked on, you may include code snippets if you believe necessary. 

When the task is completed, add a screenshot as evidence here in the comments. 

Task worth: 20pts (10pts Deadline is tomorrow!!! urgency  * 2pts Easy difficulty)

**Comment by Draygon1016** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93699133/f3272112-553b-4351-8e89-77e58a6d0b0b)

Screenshot of added documentation, for evidence.

**Comment by Andy3017** [comment]
<img width="593" alt="Screenshot 2023-09-25 at 11 56 21 AM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/d43fd4b0-5151-4fb1-ab3e-12b0e744c117">

Screenshot as evidence of updated  document

**Comment by OrdepA17** [comment]
Good work! Points have been updated.
