### ISSUE TITLE
Code Cleanup & Maintenance

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#106]
Refactoring code, renaming unclear variables, and overall structuring the code that was created in the first sprints so that they are aligned with the same dependencies

Task worth: 8pts (2pts from low priority * 4pts from intermediate difficulty)

**Comment by Jonathan-Rod** [comment]
- Refactored file names and code formatting.
- Added 'title' and 'paragraph' to styles in 'Department' component.
- Added 'surface','searchBar', and 'input' to styles in 'MySearchBar' component.
- Refactored the 'FolderIcon' component moving it outside 'Course' component.
