### ISSUE TITLE
TEAM 4 - Activity page layout

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#109]
In this task, you will focus on the creation of the page layout for the activities page. On this page, users will be able to see their notifications regarding their upcoming meetings with tutors and even messages from tutors. Do not focus on the messaging aspect of the page as that would be a separate implementation. This task is to be completed for the upcoming sprint due Monday, October 2. 

Task worth: 24pts ( 6 pts High Urgency * 4 pts Difficulty)

**Comment by gabrielroman1107** [comment]
Activity page was modified in the activityPage branch. Page has been completed and is subject to changes.

**Comment by OrdepA17** [comment]
Points have been awarded, good work!
