### ISSUE TITLE
Design Activities page style using Figma

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#11]
Assignees will be tasked with creating a draft of how they think the corresponding page should look like

**Comment by OrdepA17** [comment]
The activities page will contain a small icon that will lead to the user's profile, it will also contain either a button or tabs that upon pressing the page changes from notifications to a text chat or vice versa. Notifications will appear as a rolling feed, displaying information like "your next meeting for X class has been set for Y day." or "You completed this coruse!" The text chat will display the chats with the different tutors and upon selecting the tutor's chat it opens all the messages.

The Figma project is located here: https://www.figma.com/file/EjTKhIoC3vWCSzQZHi7duD/TEAM-4---UI-Design-(Copy)?type=design&node-id=4213%3A1335&mode=design&t=wY21h0PsI7quo7ZN-1

**Comment by OrdepA17** [comment]
Due to the nature of the text chat, a Direct Message must be made seperately and will be assigned to the member who started the designing it. This DM page includes the different text chats the user has with tutors or students. Each section displays the users profile picture, their name and most recent message.

**Comment by Draygon1016** [comment]
This is the final version of the Activities Page and is ready for review.

![Screenshot_20230909_170154_Chrome](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93699133/a0d886ae-1a37-45c3-af52-cf353c5646bb)

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams. 
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 4 Points (for team collaboration)

Total: 4 Points Awarded for each developer
