### ISSUE TITLE
TEAM 4 - Generate more Database values

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#111]
For this task, you will study the database and add values to the tables corresponding to the table. For example, add more users, add more courses, which ties in with Issue #26, and create the relations of the course schedule table, which shall be edited soon. 

Any questions, feel free to reach out.

Task worth: 16pts (4pts Medium Urgency * 4pts Intermediate Difficulty)

**Comment by OrdepA17** [comment]
Any progress regarding this task? If so, please document the changes so proper points can be awarded. Feel free to reach out if you have any questions or concerns!

**Comment by Andy3017** [comment]
<img width="1098" alt="Screenshot 2023-10-11 at 10 43 56 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/d33bf1f6-9802-4fee-8151-12713e8a2abc">
<img width="1098" alt="Screenshot 2023-10-11 at 10 44 11 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/3c477cbe-63a9-43f2-aa1b-67d8ceb1eac1">
<img width="1103" alt="Screenshot 2023-10-11 at 10 49 56 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/222f65cc-d37e-4efa-bcdb-826bc2fb025e">
<img width="839" alt="Screenshot 2023-10-11 at 11 09 25 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/0703926c-8b4e-41a4-b1ce-5545f0afd73e">

Here some screenshots as evidence of the work done

**Comment by OrdepA17** [comment]
Points have been awarded, good work!
