### ISSUE TITLE
TEAM 4 - API connections for Home Page

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#113]
In this task, you will communicate with Team 3 and determine any missing API connections that might have been overlooked during the previous milestone. This task will be marked as completed when at least 4 API connections are created. 
Bonus points for additional API connections. 

To work on this task, you may create the branch that contains the page that is going to be worked on, if is not already on the main branch, and the initial API connections (whether it is the Python, team4-api_integration branch, or the JavaScript. Team4_API_JS branch)

Task worth: 36pts (6pts High Priority * 6pts Hard difficulty)

**Comment by KVA27** [comment]
[Team 4 (1).pdf](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/files/12850940/Team.4.1.pdf)

**Comment by OrdepA17** [comment]
Looks good! Points have been awarded. Remember to make the Pull Request on the branch you worked on!
