### ISSUE TITLE
TEAM 4 - API connections for User Page

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#114]
In this task, you will communicate with Team 1 and determine any missing API connections that might have been overlooked during the previous milestone. This task will be marked as completed when at least 4 API connections are created.
Bonus points for additional API connections.

To work on this task, you may create the branch that contains the page that is going to be worked on, if is not already on the main branch, and the initial API connections (whether it is the Python, team4-api_integration branch, or the JavaScript. Team4_API_JS branch)

Task worth: 36pts (6pts High Priority * 6pts Hard difficulty)

**Comment by firecharge0** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/a72a422d-8782-421f-96fb-407b265623bf)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/222aa582-b425-4e88-8bf9-014edbf00488)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/a02aa1f7-140d-4380-8fc0-b2badc0d949f)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/6ab2a017-5c26-4f5d-ae18-8aab9d8e2605)
Added api connection for updated a users Porfile picture url as well as clearing it. Attached is code and queries used by the api.

**Comment by DanielFebles** [comment]
Added API connections for getting user names via ID and email. Code and utilized queries with successful tests attached.
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779408/a027dad6-2054-4b45-906a-955223d1951e)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779408/c16574e0-52b6-4277-99fb-c9a61c82ce30)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779408/4c5f7140-93e1-4ffa-95f1-a2dd4e03afbf)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779408/dda3d728-f732-4185-973b-8a02b95160f9)

**Comment by OrdepA17** [comment]
Good work, points were awarded when comments were made. Closing the issues no to clear the project board.
