### ISSUE TITLE
TEAM 4 - API Connections for Services Page

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#115]
In this task, you will communicate with Team 2 and determine any missing API connections that might have been overlooked during the previous milestone. This task will be marked as completed when at least 4 API connections are created.
Bonus points for additional API connections.

To work on this task, you may create the branch that contains the page that is going to be worked on, if is not already on the main branch, and the initial API connections (whether it is the Python, team4-api_integration branch, or the JavaScript. Team4_API_JS branch)

Task worth: 36pts (6pts High Priority * 6pts Hard difficulty)

**Comment by LuisAcevedo24** [comment]
![IMG-20231028-WA0001](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/90216055/2d269a64-a37a-42ce-999c-90147d244f58)

Implementad conections in the api requiered to pull the data needed for service Page.

**Comment by Andy3017** [comment]
![servicepage](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/956cc2db-425b-4a72-a1a5-5bd1d9115e50)


Implemented conections in the api requiered to pull the data needed for service Page blocked by the merging of team4-api_integration branch

**Comment by OrdepA17** [comment]
Good work, points were awarded when comments were made. Closing the issues to clear the project board.
