### ISSUE TITLE
TEAM 4 - API connections for Activity Page

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#116]
In this task, you will analyze and determine any missing API connections that might have been overlooked during the previous milestone. This task will be marked as completed when at least 4 API connections are created.
Bonus points for additional API connections.

To work on this task, you may create the branch that contains the page that is going to be worked on, if is not already on the main branch, and the initial API connections (whether it is the Python, team4-api_integration branch, or the JavaScript. Team4_API_JS branch)

Task worth: 36pts (6pts High Priority * 6pts Hard difficulty)

**Comment by Draygon1016** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93699133/d9feeb70-2a27-4615-a737-94b6a3ae4741)

These are my additions to the API for the notifications table and activity page. Upload is pending due to the merging of this branch.

**Comment by Andy3017** [comment]
![activitypage](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/97191882-1e1a-4d86-9e67-1d4e17de38e8)

Upload is pending due to the merging of this branch.

**Comment by OrdepA17** [comment]
Good work, points were awarded when comments were made. Closing the issues to clear the project board.
