### ISSUE TITLE
TEAM 1 - Tag up with team 4 

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#118]
This task involves tagging with team 4 either talking with the manager or the team about how the queries work, get comfortable to the tech stack, be confident on explaining it to team 1 and making sure that the db has everything for the profile page. 

Task points: 3 (Difficulty) * 6 (Priority) = 18 pts

**Comment by PinkSylvie** [comment]
@print-Eruki  I'm done with my report. I met with Team 4's manager on Friday so we could discuss the backend, team 1's needs from the backend, and what we need to know to be able tu use it. I'll link it [here with my findings and explanations regarding the backend](https://docs.google.com/document/d/1ZRjV6rSq50erwycuvCcc2X1DPEEdVdAxSUxxxjTCTfY/edit?usp=sharing).
