### ISSUE TITLE
Design Profile page style using Figma

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#12]
Assignees will be tasked with creating a draft of how they think the corresponding page should look like

**Comment by OrdepA17** [comment]
The profile page will areas where the user can edit their information, contact info, Bio, profile pictures, ect. For the tutors, it would 

The Figma project is located here: https://www.figma.com/file/EjTKhIoC3vWCSzQZHi7duD/TEAM-4---UI-Design-(Copy)?type=design&node-id=4213%3A1335&mode=design&t=wY21h0PsI7quo7ZN-1

**Comment by Andy3017** [comment]
<img width="343" alt="Screenshot 2023-09-09 at 9 10 35 AM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93933833/8f5049b3-4b4a-4ab9-9869-03b6140d2c7b">
This is the final version of the **Tutors Profile Page** and is ready for review

**Comment by DanielFebles** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779408/5a485914-af1a-464e-b9a7-c86012641e19)
I have also prepared the student layout as well, alongside some alternative layouts for the bio/tabs for better clarity/consistency

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams. 
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 4 Points (for team collaboration)

Total: 4 Points Awarded for each developer
