### ISSUE TITLE
Team 3 - Update Courses to query from DB

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#125]
- Update the active courses section to query from the database (set up a mock user with active courses).
- Team 4 is currently working on creating the APIs to pull data from the database.
**Hard * Urgent (6pts * 8pts ) 48pts** 
This task will be worked on by two people.

**Comment by Jvstinoo** [comment]
I have set up a function in the Database that given the 'student_id', will return a table with the student's active courses. More specifically, the course's tutor and course name. In the attached branch, the rpc call to that function has been set up and the courseCard component has been updated to get it's data from the query.

![Screenshot from 2023-10-26 17-41-52](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/5f909005-a8b2-447c-8fdd-83f98f8ac07d)

For now, I have hardcoded to query student "John Doe"'s data.
