### ISSUE TITLE
Team 3 - Adhere to the Search Page Design on the Home Page

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#130]
-Remove the "Home" label from the top of the screen.
-Modify the "Bold" style for Active Courses and Recommended Tutors.
-Adjust the border color to match the green used on the Search Page.
-Replace the purple buttons with the color: rgb(103, 80, 164).
    Intermediate * Medium (4 pts * 4 pts) = 16 pts

**Comment by yamgram7** [comment]
I will work specifically on "modify the 'Bold' style" and "replace the purple buttons" sub-tasks.

**Comment by Jvstinoo** [comment]
I have attached the branch `team3-home_page_restyling`, where all changes involving this issue will be implemented.

Done:
  - All labels at the top of the screens have been removed.
  - **Active Courses** and **Recommended Tutors** containers have been updated to match the border colors on **Search Page**.

![Screenshot from 2023-10-17 22-17-55](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/af0faf5e-e328-4c20-9a45-fef8831be40a)

**Comment by yamgram7** [comment]
My part is done: modified "bold style" of "Recommended Tutors" and Active Courses headers to replicate those of the search page and changed color of purple buttons to 'rgb(103, 80, 164)'
