### ISSUE TITLE
Team 3 - Update for Tutoring Detail Page

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#132]
-  Back Button for Tutoring Detail Page
Intermediate *  Medium (4pts * 4 pt) 16 pts

**Comment by Yabdiel1** [comment]
I have fixed the issue of no back button on the Detail Page. I have made some minor changes in the StackNavigator to support a default back button. If anyone has any questions, feel free to ask me.
