### ISSUE TITLE
TEAM 4 - Profile Picture Storage

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#135]
For this task, you will facilitate the storage of profile pictures for the User Page. This means that you will conduct research on what is the most effective way to store images within our database, specifically the Users table, and implement the fetch requests in the API.  This task shall be a feature that must be completed for Milestone 2. Here is the Supabase documentation regarding image storage to get you started.  Bonus Points for adding values to the new attribute.

https://supabase.com/docs/guides/storage

Task worth: 48pts (6pts High Priority * 8pts Advanced Difficulty) 

Created on October 15, 2023

**Comment by dylanDeJesus21** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/52340c05-a48f-44b0-b247-2c90de8ab931)

Fetch profile picture request

![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/c43f6b5d-cc5e-447b-b223-07c5c0e87a67)

Display code with test case

**Comment by OrdepA17** [comment]
Closing the issues to clear the project board.
