### ISSUE TITLE
TEAM 4 - Fix Tutor Recommendation

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#136]
For this task, you will communicate with the members of Team 3 to learn how the Tutor recommendation feature they implemented works and then fix said feature.  This is due to the Users' table being refactored and the way they accessed the data has been altered. We broke it so we shall clean up the mess basically. Get a general understanding and find ways to optimize it. This task will serve as one of the first end-to-end tasks that we shall be working on in the near future so please get a good understanding of the inner workings of the front end and how we can connect it to the backend.  Research is required!

(Hint: You can use a query to make the tutor sorting efficient and have it on the backend)

Task Worth: 48pts (6pts High Priority * 8pts Advanced Difficulty) 

Created on October 15, 2023

**Comment by firecharge0** [comment]
Upon communicating with team 3 it was found that duplicate work was being done, in which case the team decided to pivot and use the space to make a recommended courses function that would return all the courses given by the tutors currently associated with with a given student. Attached the queries that accomplish this.
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/53860f47-4430-4943-a391-e39492d30504)

![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/ad61db11-293d-4b7f-9af2-e217d0566308)

**Comment by Draygon1016** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93699133/73e15adb-0cd0-4868-a46d-2192a80cddf8)

Added fetchRecommendedCourses and fetchCourses to handle a Supabase SQL query and export the retrieved courses.

**Comment by OrdepA17** [comment]
Great work! Points have been awarded

**Comment by OrdepA17** [comment]
Closing the issues to clear the project board.
