### ISSUE TITLE
Document the information required for the courses

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#137]

**Comment by Yahid1** [comment]
Where do I put the documentation?

**Comment by panchi64** [comment]
Ideally the github wiki, otherwise a publicly available link that is placed in a readily available location (like a forum discussion)

**Comment by Yahid1** [comment]
Ok github wiki

**Comment by panchi64** [comment]
Was this completed? It shows up as Ready to Start for me

**Comment by Yahid1** [comment]
I am adding it today

**Comment by Yahid1** [comment]
This is what I did:
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/94016523/81556322-4dc7-4bd6-a08a-d47ef42b2179)

Found here:
https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/wiki/Search-Page#course-component

**Comment by Yahid1** [comment]
If something needs to be added or change please tell me
