### ISSUE TITLE
TEAM 1 - Create a section in the documentation to track all the changes

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#139]
This task involves creating a section in the documentation where we are going to state what were the changes for the current milestone (2)

Task points: 5 (Priority) * 3 (Difficulty) = 15 pts

**Comment by jacorderopr** [comment]
The section has been created as well as the updating of this section as milestone's 2 changes are being implemented.
