### ISSUE TITLE
Design Direct Message page style using Figma

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#14]
Due to the nature of the text chat, a Direct Message must be made separately and will be assigned to the member who started the designing it. This DM page includes the different text chats the user has with tutors or students. Each section displays the users profile picture, their name and most recent message.

Additional ideas are welcomed and encouraged! Just make sure to add them to the Idea Pool!

The Figma project is located here: https://www.figma.com/file/EjTKhIoC3vWCSzQZHi7duD/TEAM-4---UI-Design-(Copy)?type=design&node-id=4213%3A1335&mode=design&t=wY21h0PsI7quo7ZN-1

**Comment by gabrielroman1107** [comment]
This is the final version of the DM Page and is ready for review.
<img width="405" alt="Screenshot 2023-09-08 at 2 33 43 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/89166066/9fef43c3-94fb-4b9b-9ad5-d8fadba93a0d">

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams. 
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 0 points (solo task and met expectations)

Total: 4 Points Awarded to the  developer
