### ISSUE TITLE
Team 1 - Make the corections for describing the secondary goals

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#144]
Refer to the punctuation given on the proposal.

Task points: 7 (Priority)* 3 (Difficulty) = 21 pts

**Comment by FrancesC8** [comment]
@print-Eruki I finished defining the secondary goals and added them in the documentation, based on the feedback. The secondary goals can be found in the section 1.4 in the  [Documentation](https://docs.google.com/document/d/1BFH-jMxeQUkulSXozFVO41hrATL9jMLq3H0X-UzbsDk/edit?usp=sharing). Ready for review.

**Comment by print-Eruki** [comment]
Great job!
