### ISSUE TITLE
TEAM 1 - Reach out to the professor to understand and correct secondary goals section in documentation

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#145]
Task points: 7 (Priority) * 3 (Difficulty) = 21 pts

**Comment by sandy-marrero** [comment]
https://sistemaupr-my.sharepoint.com/:v:/g/personal/marko_schutz_upr_edu/Eff0MuJI9nFGkk9XSZih4NkB2srABe3agMR__v1ZQ9vC_w

Meeting with professor for getting more information about secondary goals.
