### ISSUE TITLE
TEAM 1 - Schedule a review session with a Teacher Assistant

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#147]
Task points: 7 (Priority) * 3 (Difficulty)= 21 pts

**Comment by PinkSylvie** [comment]
@print-Eruki  @Ezequiel-Mendez Finished the document detailing the documentation feedback given in the schedueled meeting with TA Alejandro Behar Gutierrez. [Here's the link for review!](https://docs.google.com/document/d/10xaOx9pZRCp21T4tBaqqvekM2Rug17MIQBEfnlcbdk8/edit?usp=sharing)
