### ISSUE TITLE
TEAM 1 - Work on correcting "The guidelines on forming insightful function signatures"

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#148]
Refer to the punctuation given on the proposal

Task points: 7 (Priority) * 3 (Diffculty) = 21 pts

**Comment by FrancesC8** [comment]
@print-Eruki I finished creating the guidelines on forming insightful function signatures and added them in the documentation, based on the feedback. The guidelines on forming insightful function signatures can be found in the section 2.1.6 in the [Documentation](https://docs.google.com/document/d/1BFH-jMxeQUkulSXozFVO41hrATL9jMLq3H0X-UzbsDk/edit?usp=sharing). Ready for review.
