### ISSUE TITLE
Separate DM page from Activity Page

### ISSUE THREAD

**Issue by gabrielroman1107** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#15]
Since we would like to access al the chats individually, we would benefit from two different pages. The DM page would allow us to see more organized the chats with the tutors and would help on not letting one page become too saturated with information.

**Comment by OrdepA17** [comment]
It has been closed since it was a duplicate of an idea within Team 4's Backlog. If this is referring to creating the feature then the issue shall be reopened and assigned accordingly.
