### ISSUE TITLE
TEAM 4 - Create Database special case values

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#150]
For this task you will create new values within the database that meet special cases that can occur within our app. Examples of these are: a single tutor is offering multiple classes, a tutor is offering the same class at different times, a single student is enrolled in multiple courses with the same tutor, ect. Feel free to add as many test cases and screenshot the new values as evidence of completion!

Task worth: 8pts (2pts Easy difficulty * 4 Medium Urgency)

**Comment by dylanDeJesus21** [comment]
I added two more cases to the database:
**Student that is taking a different course with same tutor**
![Same_stud_same_tutor_1](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/8741b620-4953-4481-a289-6498d86f7219)

![Stud_Tutor_2](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/5ebc20f8-2dbd-46c3-ab84-0bf41a4c466c)

![stud_tutor_3](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/b0e28281-c205-4f4d-8a62-514c1ea1ade2)

**Same course, same time, different tutor**
![same_course_same_time](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/6897a815-5e4b-4d49-97a7-cf3a5cadc195)

**Comment by gabrielroman1107** [comment]
10 new rows were added in the tutoring_courses table. In the blue we see different courses offered by the same tutor. In the red we see the same course offered by different tutors. In the green we see different courses offered by different tutors at different times and at different locations.

<img width="1440" alt="Screenshot 2023-10-22 at 6 55 33 PM" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/89166066/16660cae-5182-4a16-bc42-1c5ccc90191a">

**Comment by OrdepA17** [comment]
Good work! Points have been awarded!
