### ISSUE TITLE
Setup project ESLINT and/or Prettier configuration files

### ISSUE THREAD

**Issue by williammartinez10** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#151]
The configuration file is expected to enforce:
 - `camelCase` for variable names
 - `kebab-case` for file names
 - `UpperCamelCase` for components in individual .jsx files
 - double quotes `" "` for text
 - line length limit of 80-120 characters
 - indentation of `2 spaces` per tab

**Comment by williammartinez10** [comment]
Once the configuration files are setup, should these rules and styles also be applied?

**Comment by williammartinez10** [comment]
^ @panchi64 
(For example, change the filenames to match the new standard)

**Comment by panchi64** [comment]
If setup correctly the configuration file should automatically tell the other teams that their code doesn't follow the standards. I don't know if that is what you're asking or if you want to apply those styles manually.

**Comment by williammartinez10** [comment]
I meant that if i needed to apply the changes manually. Currently, in the branch "configuration-files", if the standards are not met, there are certain errors or warnings that will show up. Since this branch is based off of the main branch, it would be best to leave it as it is currently (with the errors and warnings showing up). Otherwise, if I were to change everything that is not meeting the standards, other branches that are based off of the main branch as well (before this branch was created), would have discrepancies and they wouldn't be so straight forward to merge.

**Comment by williammartinez10** [comment]
Is that okay? I don't know, maybe I'm overthinking it😅

**Comment by panchi64** [comment]
> I meant that if i needed to apply the changes manually. Currently, in the branch "configuration-files", if the standards are not met, there are certain errors

Let me catch up real quick 😭. Do the errors come from a configuration file you've generated/created? Or is it more of a preemptive mention that errors will rise?

**Comment by williammartinez10** [comment]
![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/77518982/0e6e2fe5-591e-49ad-860b-6b99d09abc2c)



![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/77518982/947f0946-e399-45cf-89eb-049b053527b5)

Yes, they come from the configuration files. This is what what is currently being shown in terms of the filenames.

**Comment by panchi64** [comment]
Goootcha 👍. Make a pull request with that configuration file, I'll override and directly merge it to main. 

If you want to fix the errors that pop up on the Search page's code feel free to. But lets leave (for the time being) those errors to show up on other team's IDEs and for them to solve them accordingly.

I'll also let every other team know that their code should follow those standards and to publish their fixes ASAP.

**Comment by williammartinez10** [comment]
Perfect, I'll make the pull request now.
