### ISSUE TITLE
Team 3 - Design Home Page 

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#16]
- An area for the courses where the student is actively taking tutoring.
- An area for the courses that the student is taking that same semester.
 Task Worth: 8 pts (2pts from low priority * 4pts form Intermediate difficulty)

**Comment by Jvstinoo** [comment]
Design for the Home page has been completed. Home page contains sections **Tutoring** and **Recommended Tutors**.

- Tutoring: All courses for which the user is enrolled in with a tutor will appear here.

- Recommended Tutors: Based on the courses the student is taking that semester, tutors will be recommended. Each tutor component contains their name, what subjects they teach, and their rating. Finally, they can view their full profile by clicking on the **View Profile** button.

Prototype link: [Prototype](https://www.figma.com/proto/BDMvJx76OaeqELnybmfBp4/Team-3---Draft-Tutoring-App?type=design&node-id=6464-59&t=ApS1SkJxLsCf7MJa-1&scaling=scale-down&page-id=6036%3A164056&mode=design)

Team Figma Project: [Team Project](https://www.figma.com/file/BDMvJx76OaeqELnybmfBp4/Team-3---Draft-Tutoring-App?type=design&node-id=6036%3A164056&mode=design&t=eA9VEKYVkZajEYhA-1)
