### ISSUE TITLE
TEAM 1 - Fix/Update interface requirements

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#161]
The documentation can be found in the devcon 1 in discord

Task points: 3 (Difficulty) * 7 (Priority) = 21 pts

**Comment by Kiam11** [comment]
No adding was needed, but fixed the wording on some parts, in words like "must" to "shall"

**Comment by Kiam11** [comment]
Improved the overall readability on some sentences and reviewed all the statements

**Comment by Kiam11** [comment]
Added 1.5.3  and 1.5.4 to the log book
