### ISSUE TITLE
TEAM 2 - Sign-up Page development

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#167]

**Comment by panchi64** [comment]
I've moved this to "In Progress" since I've seen some activity from you in the Discord channel with regards to this task.

**Comment by Jonathan-Rod** [comment]
Sign-up Page represents a registration form in a React Native application. Users can enter their first name, last name, email, and password, and then click the "Sign Up" button to complete the registration. Validation functions are provided to ensure the accuracy of the entered data, and a pop-up message is displayed to inform the user about the registration outcome.

**Comment by Jonathan-Rod** [comment]
**Sign-up Page** represents a registration form in a React Native application. Users can enter the following information:

1. `First name`
2. `Last name`
3. `Email`
4. `Password`

They can then click the **"Sign Up" button** to complete the registration. Validation functions are provided to ensure the accuracy of the entered data, and a pop-up message is displayed to inform the user about the registration outcome.

**Comment by Jonathan-Rod** [comment]
Here is the list of points and errors to be implemented:

- [ ] **Name and Last Name:**
  - [ ] Error Case 1: Name is blank.
  - [ ] Error Case 2: Last name is blank.
  - [ ] Error Case 3: Name or last name contains invalid characters.

- [ ] **Email:**
  - [ ] Error Case 4: Email is blank.
  - [ ] Error Case 5: Email is not valid.
  - [ ] Error Case 6: Email is already registered.

- [ ] **Password:**
  - [ ] Error Case 7: Password is blank.
  - [ ] Error Case 8: Password is too short.
  - [ ] Error Case 9: Password does not meet security requirements (e.g., must contain uppercase, lowercase, and special characters).

- [ ] **Password Confirmation:**
  - [ ] Error Case 10: Password confirmation does not match the original password.

- [ ] **Successful Registration:**
  - [ ] Success Case: All data is valid, and the user is registered successfully.

**Comment by yahirfigueroa** [comment]
I think that all those registration considerations are perfect, I think that they are the necessary ones. Maybe error 7 and 8 could be merged. Of the current branch and of what I tested, the things implemented work very well. Ui wise maybe it will be good to implement the eye in the password to see the letters. But everything else looks clean.

**Comment by Jonathan-Rod** [comment]
- [x] **Name and Last Name:**
  - [x] **Missing First Name:** Please enter your first name.
  - [x] **Missing Last Name:** Please enter your last name.
  - [x] **Invalid Characters:** Your first name and last name should only contain letters.
 
- [ ] **Email:**
  - [x] **Missing Email:** Don't forget to enter your email.
  - [x] **Invalid Email Format:** Please enter a valid email address.
  - [ ] **Email Already Registered:** This email is already in use. Please use a different one.

- [x] **Password:**
  - [x] **Missing Password:** You need to create a password.
  - [x] **Short Password:** Your password should be at least 8 characters long.
  - [x] **Weak Password:** Your password must contain at least one uppercase letter, one lowercase letter, and one special character.
  
- [x] **Password Confirmation:**
  - [x] **Password Mismatch:** The password confirmation doesn't match the original password. Please re-enter it.
