### ISSUE TITLE
Team 3 - Design Service Page

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#17]
- A search bar for courses
- A section that divides the classes by department (ie. Math,   Physics, Electronics, Software, Business, etc)
- Those sections contain all the respective courses from that department.
- When the course has been selected a list of available tutors appears with their availability
Task Worth: 8 pts (2pts from low priority * 4pts form Intermediate difficulty)

**Comment by Yabdiel1** [comment]
Created a browser page/service, where we can find Categories for each class. Also added a filter bar to be able to search for the class you are looking for. TODO: Design what would happen if one of the categories is clicked, how would that look like? Let me know if something must be added or changed.
