### ISSUE TITLE
Team 3 - Design Profile/Account Page

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#19]
- User Profile Information
- User's name, username, or display name.
- Profile picture or avatar.
- Contact information (email, phone number, etc.).
- Bio or short description.
Task Worth: 8 pts (2pts from low priority * 4pts form Intermediate difficulty)

**Comment by ilikecheese117** [comment]
I'll try to work on this today and tomorrow. I'll update the team if I reach any level of progress.

**Comment by ilikecheese117** [comment]
Finished a possible design for profile page
