### ISSUE TITLE
Academic Achievement Tracker between Student/Tutor (Design)

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#20]
Have an academic tracker where the student places his grades (under confidentiality and consent of both parts) so the tutor can monitor if the student is benefitting from the tutoring sessions.

**Comment by dylanDeJesus21** [comment]
![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/1b794b88-b5a9-4c64-821d-4c23ddea9db4)

Profile page + Schedule page


![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/ea7b52b6-1e15-4e4c-988c-16227f34c2cb)

Home page + Course progress page (Academic Tracker)

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams.
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 0 points (solo task and met expectations)

Total: 4 Points Awarded to the developer
