### ISSUE TITLE
TEAM 4 - Final Touches to Database

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#202]
This task is to take any feedback from the other teams, where they understand that the information or use case of the app is not being handled or something that was overlooked previously and has to be added to the database. Since this task will remain open until all cases are covered then Urgency will be set to Medium and Difficulty to Intermediate, since we have already facilitated many fields before. 

ANY DEVELOPER IS WELCOME TO COMMENT ON THIS TASK REGARDING THE DATABASE! 

All feedback is welcome and any questions regarding its functionality we will answer to the best of our abilities. 

Task Worth: 16pts (Urgency Medium 4pts * Difficulty Intermediate 4pts)

**Comment by Jeisen515** [comment]
Feedback was taken and changes has been developed.
