### ISSUE TITLE
TEAM 4 - User Authentication Implementation

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#204]
In this task, you will work on the user authentication for the app. Team 2 is already doing research on how the authentication should work, reference Issue #191 for their findings. This task will be marked as complete once a successful login is demonstrated, shows the correct information for the given user, and also the successful creation of a new user, seeing their information on the Profile page. 

Task worth: 16pts (Urgency Medium 4pts * Difficulty Intermediate 4pts)

**Comment by DanielFebles** [comment]
Finished sign in/up/out implementation (requires more testing).
