### ISSUE TITLE
TEAM 1 - Adapt the styles and theme of the profile page with the rest of the application

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#205]
Tag up with team2 and/or team3 to see and understand what is needed in order to get that done. 
Task points: 5 (Priority) * 4 (Difficulty) = 20 pts

**Comment by PinkSylvie** [comment]
**[The pull request for this task](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/pull/240)**
