### ISSUE TITLE
TEAM 3 - 1.2.1 Current Situation - Home Page Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#206]
Complete the section [1.2.1 Current Situation] in the Home Page Documentation. 

Link to the Doc: https://docs.google.com/document/d/1EO-CfbITlsSfOFOkrinAeka8FzPLD_8EwZo7P-gpDIY/edit?usp=sharing

(5 pts ) Medium-High Urgency * (2 pts) Easy Difficulty = 10 pts

**Comment by yamgram7** [comment]
Done: 

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779562/2ed2835f-aaee-40f3-aa3c-990e19504f18)
