### ISSUE TITLE
TEAM 3 - [1.2.3 Ideas] - Home Page Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#208]
Complete the section [1.2.3 Ideas] in the Home Page Documentation. 

Link to the Doc: https://docs.google.com/document/d/1EO-CfbITlsSfOFOkrinAeka8FzPLD_8EwZo7P-gpDIY/edit?usp=sharing

(5 pts ) Medium-High Urgency * (2 pts) Easy Difficulty = 10 pts

**Comment by Jvstinoo** [comment]
Done:

![Screenshot from 2023-11-25 16-23-49](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/d2ec926f-52a8-4b6f-99a2-e9d4be77ff1e)
