### ISSUE TITLE
TEAM 3 - [1.3.2 - Synopsis] - Home Page Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#211]
Complete the section [1.3.2 - Synopsis] in the Home Page Documentation. 

Link to the Doc: https://docs.google.com/document/d/1EO-CfbITlsSfOFOkrinAeka8FzPLD_8EwZo7P-gpDIY/edit?usp=sharing

(5 pts ) Medium-High Urgency * (2 pts) Easy Difficulty = 10 pts

**Comment by Jvstinoo** [comment]
Done:

![Screenshot from 2023-11-25 16-24-02](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/ce9a891f-a700-44bd-af8d-488a3a7aae50)
