### ISSUE TITLE
TEAM 3 - [3.1 Concepts Analysis] - Home Page Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#228]
Complete the section [3.1 Concepts Analysis] in the Home Page Documentation. 

Link to the Doc: https://docs.google.com/document/d/1EO-CfbITlsSfOFOkrinAeka8FzPLD_8EwZo7P-gpDIY/edit?usp=sharing

(5 pts ) Medium-High Urgency * (2 pts) Easy Difficulty = 10 pts

**Comment by Jvstinoo** [comment]
Done:

![Screenshot from 2023-11-25 17-07-24](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/9130d812-5685-4d42-b4dd-a4f85d998d66)
