### ISSUE TITLE
TEAM 3 - Update UML Sequence Diagram - [Lecture Topic Task]

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#232]
Update the UML Sequence Diagram created in Milestone 2.

(5 pts ) Medium-High Urgency * (2 pts) Easy Difficulty = 10 pts

**Comment by Techno857** [comment]
[HomePage UML Sequence Diagram.pdf](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/files/13482935/HomePage.UML.Sequence.Diagram.pdf)
![HomePage UML Sequence Diagram](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93626812/54c98a8b-f4dd-4773-a562-bc47fe21644e)
