### ISSUE TITLE
TEAM 1 - Make the corrections for "Algebras and closure under operations." from milestone 2

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#234]
Task points: 5 (Priority) * 6 (Difficulty) = 30 pts

**Comment by jacorderopr** [comment]
Initial Corrections for algebras and closures have been implemented and checked with managers and developer teammates. Another task regarding seeking for the professor’s feedback will be done next.
