### ISSUE TITLE
TEAM 1 - Receive feedback from the professor and TA to ensure that "Algebras and closure under operations" is correct

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#235]
Task points: 5 (Priority) * 2 (Difficulty) = 10pts

**Comment by jacorderopr** [comment]
Emailed TA/prof and received initial feedback regarding the Algebras and closure under operations. Feedback will be implemented in documentation and then will reach out to them again to see if new implementation is optimal.
