### ISSUE TITLE
TEAM 1 - Merge the rating component with the branch team1-main

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#244]
Jose julian branch for more info contact him. Merge conflicts are being resolved by you
Task points: 5 (Difficulty)* 5 (Priority)= 25pts

**Comment by jorge-torres33** [comment]
Solved merge conflicts https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/tree/team1-main
