### ISSUE TITLE
TEAM 1 - Add a section in the documentation for changes made for milestone 3

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#246]
@PinkSylvie please add your changes that you made for this milestone relating to matching the theme of the profile page with the rest of the apps.

Task points: 5 (Priority) * 4 (Difficulty) = 20pts

**Comment by PinkSylvie** [comment]
@print-Eruki To fix the complaints received last milestone regarding the log book, I changed the _" Documantation Milestone Changes Logbook"_ into just _"Milestone Changes Loogbook"_. And added the color to indicate changes for this milestone and a log on the changes I did on this milestone:



![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93553908/ae0629a8-e38a-4be6-b695-91d5365d6fa6)



![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93553908/d731fb15-e20c-4dac-bd65-496bd36a4258)
