### ISSUE TITLE
TEAM 1 - [Lecture Task] Create a simple flowchart/UML Diagram for changing the profile picture

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#247]
Task points: 5 (Difficulty) * 5 (Priority) = 25 pts

**Comment by CaribbeanCool** [comment]
https://lucid.app/lucidchart/f31e98d8-2784-4328-b265-78991c64636e/edit?invitationId=inv_9d8dbb5b-feff-4771-9e6b-5058cecb9850
