### ISSUE TITLE
TEAM 1 - Moved all our designs into a managers Figma link

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#25]
The task revolves on moving all the team designs into this link:  https://www.figma.com/file/8tK1xVyzM5uuLMhPdlKn3S/Final-Draft?type=design&node-id=6036%3A164056&mode=design&t=7JaDKdyOe99YHbNj-1 

Please feel free to ask the team members their link or images in order to complete them. In case a team member does not response please let me know and I will take the necessary actions. If a team member did not do it in a figma, please add a picture instead to the link.

Task points: 4 points

**Comment by PinkSylvie** [comment]
[All designs should be in the figma with all their components - ready for review](https://www.figma.com/file/8tK1xVyzM5uuLMhPdlKn3S/Final-Draft?type=design&node-id=6036-164056&mode=design&t=CRonWQrBOOivdFbm-0) @print-Eruki

**Comment by PinkSylvie** [comment]
Done!
