### ISSUE TITLE
TEAM 4 -  Domain Description: Stakeholder Identification [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#264]
In this task you will identify and describe stakeholder groups relevant to the tutoring app project, including students, tutors, and administrators. Maintain clean documentation practices and add your documentation here: 

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by DanielFebles** [comment]
Documentation made.
