### ISSUE TITLE
TEAM 4 -  Domain Description: Persona Development [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#265]
In this task, you will develop detailed personas for key stakeholders, going beyond user stories to bring the personas to life with rich characteristics and motivations. Make sure to follow clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by Andy3017** [comment]
Done.
