### ISSUE TITLE
TEAM 4 -  Domain Facets Exploration: Relevant Domains [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#266]
In this task, you shall explore and document relevant domain facets for the tutoring app, considering aspects like user engagement, payment processing, and content delivery. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by firecharge0** [comment]
Documentation added to the google docs depicting relevant domain Facets.
