### ISSUE TITLE
TEAM 4 - Business Processes: Stakeholder-Specific Processes [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#267]
In this task, you shall describe at least one substantial business process for each stakeholder group, such as the process of scheduling a tutoring session for a student or managing tutor availability. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by KVA27** [comment]
task already uploaded in the document
