### ISSUE TITLE
TEAM 4 - Interface Requirements: Shared Data Initialization [Lecture Topic Task] 

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#269]
In this task, you shall analyze and document shared data initialization requirements, specifying how user data is initialized and updated within the system. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 8 pts (2pts Priority * 4pts Difficulty)

**Comment by JadiellMV** [comment]
Task done successfully!
