### ISSUE TITLE
Course component

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#27]
This task involves the creation of the react native component that will envelope the summarized information of a course found within the services page. This component is expected to expand and show the user the available tutors for a given course.

Task worth:  24pts (6 pts from high priority * 4 pts from intermediate difficulty)

**Comment by Yahid1** [comment]
Is this component a list of all the tutors for that course and does that include creating a course button that will be clickable for it to then expand into the list??

**Comment by panchi64** [comment]
No, it should be a component housing the course information with space to place a list of other components inside so that whatever tutors are available are shown within the course. Think of an accordion UI component

**Comment by panchi64** [comment]
Any progress so far? Anything I can help with?

**Comment by panchi64** [comment]
https://callstack.github.io/react-native-paper/docs/components/List/ListAccordion/
