### ISSUE TITLE
TEAM 4 - Interface Requirements: Machine-Machine Dialogs [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#271]
In this task, you shall specify machine-machine dialog requirements, focusing on communication between system components, such as notifications triggering backend processes. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 8 pts (2pts Priority * 4pts Difficulty)

**Comment by JadiellMV** [comment]
Task done successfully
