### ISSUE TITLE
TEAM 4 - Interface Requirements: Physiological Requirements [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#272]
In this task, you shall identify and document physiological requirements, considering user accessibility, readability, and overall user experience. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by KVA27** [comment]
task already uploaded in the document
