### ISSUE TITLE
TEAM 4 - Software Design: Component Collaboration [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#276]
In this task, you shall analyze requirements and document components that collaborate to satisfy them, focusing on the interaction between the backend and frontend components. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 8 pts (2pts Priority * 4pts Difficulty)

**Comment by JadiellMV** [comment]
Task done successfully
