### ISSUE TITLE
TEAM 4 -  Software Design: Scenario Validation [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#277]
In this task, you shall use a major business process as a scenario to validate the software design, demonstrating how components collaborate to fulfill user interactions on the activity page.  Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by firecharge0** [comment]
Documentation regarding the validation of scenarios has been added to the google doc.
