### ISSUE TITLE
TEAM 4 - Risk Analysis: Countermeasure Exploration [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#280]
In this task, you shall explore and document countermeasures for identified risks, detailing strategies to mitigate or eliminate potential issues. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by firecharge0** [comment]
Countermeasure exploration for determined risks added to the google docs documentation.
