### ISSUE TITLE
TEAM 4 -  Risk Analysis: Countermeasure Evaluation [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#281]
In this task, you shall evaluate the effectiveness of the identified countermeasures, considering their feasibility, cost, and overall impact on risk mitigation. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by Jeisen515** [comment]
I developed and wrote the effective evaluation for the countermeasures and it is ready for feedback.
