### ISSUE TITLE
TEAM 4 - Risk Analysis: Updated Requirements [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#282]
In this task, you shall update the project documentation to reflect new or changed requirements resulting from the risk analysis cycle, providing justifications for these updates. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 8 pts (2pts Priority * 4pts Difficulty)

**Comment by Draygon1016** [comment]
Done, everything can be found in the section "#282 Risk Analysis: Updated Requirements
" of https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit
