### ISSUE TITLE
TEAM 4 - Automated Tests: Notification Functionality [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#288]
In this task, you shall implement automated tests specifically focusing on the notification functionality within the activity page, ensuring reliable and consistent notification delivery. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by Jeisen515** [comment]
Completed the task
