### ISSUE TITLE
TEAM 4 - Completeness: Requirements Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#289]
In this task, you shall verify that requirements for all implemented features are fully documented, addressing both functional and non-functional aspects. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by KVA27** [comment]
Document has been verified
