### ISSUE TITLE
TEAM 4 - Completeness: User Acceptance Testing [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#294]
In this task, you shall outline plans and procedures for user acceptance testing, specifying criteria for evaluating the app's functionality and user experience. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by Andy3017** [comment]
Done. All the User Acceptance Testing to evaluate the app can be found in the doc, https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing
