### ISSUE TITLE
TEAM 4 - Completeness: User Documentation [Lecture Topic Task]

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#296]
In this task, you shall provide user documentation for the activity page, including a guide on accessing and managing notifications within the tutoring app. Maintain clean documentation practices and add your documentation here:

https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit?usp=sharing

Task worth: 4 pts (2pts Priority * 2pts Difficulty)

**Comment by Andy3017** [comment]
Done. All the user documantation for the activity page can be found on the doc, https://docs.google.com/document/d/10TcwRsh7Nc7pa2sH9hg3kkWhhfgv8dLAqwaQx2J-5W4/edit
