### ISSUE TITLE
Recycling the navbar from the previous sprint and integrating it to this sprint

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#30]
This task involves the migration (if necessary) of the react native component that envelopes the links to the different pages of the app.

Task worth: 12pts (6 pts from high priority * 2 pts from easy difficulty)

**Comment by panchi64** [comment]
Any update on this? Asking because it's still in the "New" part of the backlog.

**Comment by yahirfigueroa** [comment]
> Any update on this? Asking because it's still in the "New" part of the backlog.

I assume the navbar is the tab that is below on the team 1 branch which has the home, search, activity and profile tab right?  If so, do I should wait for the services pages to be implemented to check if the navbar is correctly linked to the other pages?

**Comment by panchi64** [comment]
Yes. Don't wait for everything to be implemented, since the Navbar is a core part of the application. Just make sure that it can independently work and that its not hardcoded to one single page. If possible I'd also appreciate any documentation as to where the code for the Search/Services page could be placed within the code, I'm a bit confused as to where the code for said page could be placed/created.

**Comment by yahirfigueroa** [comment]
Hey, will the service page will be something that will also be in the navbar, or in which section of the app it will be available?

**Comment by panchi64** [comment]
It is, it's just called Search. Search Screen in the code

**Comment by yahirfigueroa** [comment]
If after checking the code and getting to the conclusion that the navbar from the previous sprint is well implemented, what should I do?

**Comment by panchi64** [comment]
Document it I guess (?) Does anyone else have any idea as to what else could be done?

**Comment by panchi64** [comment]
Up to you chief, whichever you think will help out the most.

**Comment by yahirfigueroa** [comment]
[Navigation Bar Documentation- Yahir Figueroa.docx](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/files/12654396/Navigation.Bar.Documentation-.Yahir.Figueroa.docx)

**Comment by yahirfigueroa** [comment]
Please check the documentation from the navigation bar I made, is there is something wrong with the format or anything, please tell me and I will fix it, I tried to understand the code the best I could because I had never used Javascript.

**Comment by panchi64** [comment]
If possible put it somewhere where others can reach it. Not in the comments of an issue that can be lost within the many others being created daily. Maybe make a discussion thread to place documentation for things (?)
