### ISSUE TITLE
TEAM 1 - [Lecture Task] Risk assessment profile page external factors

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#305]
After identifying the risk that may be occurred on the profile page due to external factors, assess them and find ways to solve them

Task points: 2 (Priority)* 3 (Difficulty) = 6 points

**Comment by CaribbeanCool** [comment]
# Risk Assessment for Uploading a Profile Picture in a Tutoring App Web-App

## Inappropriate or offensive content:

- Likelihood: Medium
-  Impact: High
- Mitigation: Implement an image moderation system to detect and flag inappropriate content.
- Recommended action: Establish a clear image policy that defines acceptable and prohibited content.

## Privacy violations:

- Likelihood: Medium
- Impact: Medium
- Mitigation: Clearly communicate image usage policies and obtain user consent for image storage and display.
- Recommended action: Clearly inform users about image usage practices and obtain explicit consent for storage and display.

## Security vulnerabilities:

- Likelihood: Medium
- Impact: High
- Mitigation: Utilize secure image upload and storage practices, including proper file type validation and encryption.
- Recommended action: Implement secure image upload protocols, file type validation, and encryption measures.

## Performance issues:

- Likelihood: Low
- Impact: Medium
- Mitigation: Implement image compression and optimization techniques to minimize loading times.
- Recommended action: Optimize images for faster loading by using appropriate compression techniques, resizing, and file format selection.

## Accessibility concerns:

- Likelihood: Medium
- Impact: Medium
- Mitigation: Ensure alternative text descriptions are provided for images to accommodate users with visual impairments.
- Recommended action: Provide alternative text descriptions (alt text) for all uploaded images to enhance accessibility for visually impaired users.
