### ISSUE TITLE
Database optimizations

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#307]
The database does not account for rating and user/tutor distinguishing. These optimizations should enable them to be used on the frontend.

**Comment by Yahid1** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/94016523/795f66fb-6d99-4976-9843-0ea9ff1bee7f)

Works very well with my prototype of data tables

**Comment by Yahid1** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/94016523/f49730b2-6d93-4a86-a55a-24a714f8836c)

Works with main db and all data. Still needs some improvements for later.
