### ISSUE TITLE
Javascript handling of API information

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#37]
This task involves the processing of information received from the api and handing it over to the javascript code for its use within the UI.

Task worth: 24pts (6 pts from high priority * 4 pts from intermediate difficulty)

**Comment by Jonathan-Rod** [comment]
The "MySearchBar" component displays a text field that, when modified, calls the "handleSearch" function. In this function, logic will be implemented to gather information from the database and will display the contents that, according to the implemented logic, are correlated.

**Comment by RicardoJRSs** [comment]
The file that will be created would be in a separate folder or one of the already existing folders?

**Comment by panchi64** [comment]
I think it might be better to have all of the core logic of the API separated from the frontend code. However since this would be a connection from the API to the frontend maybe it's not necessary to place it elsewhere.

**Comment by RicardoJRSs** [comment]
The API Handling in JavaScript branch has the outline of how the future handling will look like when the API is created. It takes the url of the API and fetches the data to be handled in JavaScript. For now it is assumed that the data would be user based so there is an outline of how the user data would be stored in object of a user class to be used and handled.
