### ISSUE TITLE
TEAM 4 - Database setup

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#38]
~~Once the type of database has been decided, this task involves the creation of the database and implementing whatever structure was decided.~~

~~This is not expected to be delivered this sprint and is considered a long term task with a high reliance for the rest of the project.~~

~~Task worth: 40pts (4pts from medium priority + 10pts from expert difficulty)~~

**Comment by OrdepA17** [comment]
The database setup shall be part of the next sprint so urgency has been adjusted to high.  Team 4 will work on different components of the database during this sprint. Feel free to add any resources found that may facilitate the work of the tasks in the comments, as well as any ideas or discussions regarding the initial setup.

Task worth: 60pts (6pts from medium priority + 10pts from expert difficulty)

**Comment by Jeisen515** [comment]
Created the database on Supabase. It has 3 initial tables and multiple tuples.  

![Screenshot 2023-09-21 230254](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72313954/fe8b0b65-446d-45e8-8bea-f25e59e47fd1)
![Screenshot 2023-09-21 230237](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72313954/27b04918-4ebd-4e90-ab6e-49e767db301c)
[Test_program.txt](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/files/12696330/Test_program.txt)
![Screenshot 2023-09-21 230317](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72313954/678a132b-22e8-46dd-add4-b0f253a12215)

supaURL: https://qunwadbiwbycvmgscyyg.supabase.co
APIkey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bndhZGJpd2J5Y3ZtZ3NjeXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUzNDAxNjcsImV4cCI6MjAxMDkxNjE2N30.nlr1UhwV5dmZKh2uoCWV0mTeKAdGAznspCqk5oBxQYs

**Comment by gabrielroman1107** [comment]
Here is the initial Database Schema, it was designed with the purpose to be able to allow the teams to store, access, and test their implementations. This schema is subject to change.

<img width="494" alt="ER Diagram - Tutoring App" src="https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/89166066/a1d11bec-5e40-4785-98d5-fb30093dd4c9">

**Comment by OrdepA17** [comment]
Good work! Points have been awarded.
