### ISSUE TITLE
design the profile tab

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#4]
Design a profile tab for the application in Figma as an initial design idea for the platform.

**Comment by panchi64** [comment]
The initial idea of this page was for it to contain the following information:

Student/Tutor View:
- Whatever you deem is necessary for a profile. If you do add something to it, put it in the ideas pool! Anything you can think of is viable 😄

[Link to Figma page](https://www.figma.com/file/i4Tz0s1kqkIRI2JLh3KuKR/Main-App-Tabs---Designs?type=design&node-id=0%3A1&mode=design&t=kP3B1RwCZ2xYvWrV-1)

**Comment by RicardoJRSs** [comment]
https://www.figma.com/file/OK4PHDJnCRSdEita6F0vMI/Untitled?type=design&t=Lh7l3kRBCvsHm9gv-6

**Comment by williammartinez10** [comment]
https://www.figma.com/file/r0x8CrhV4ydXmEMideI0vH/Tab-Designs---Tutoring-App?type=design&node-id=0%3A1&mode=design&t=ylPZ26G8mOlDwGxf-1

**Comment by gustavosotero** [comment]
https://www.figma.com/file/GF9yAnzFR7j5mJvkJLZex6/Tab-Designs-for-the-App-Gustavo-Sotero?type=design&mode=design&t=xvR7DwvW8qs2igVE-1
