### ISSUE TITLE
Tutor component

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#41]
This task involves the development of the react native component that will represent a summarized version of the available tutors for a given course.

Task worth: 24pts (6pts for the high priority * 4pts for the intermediate difficulty)

**Comment by Jonathan-Rod** [comment]
Do we already know the properties of this tutor component?

**Comment by panchi64** [comment]
General information like their name and a rating (ie 3.5/5 ⭐️)

**Comment by panchi64** [comment]
https://callstack.github.io/react-native-paper/docs/components/ActivityIndicator

As a resource for the use and various options of the React Native Components

**Comment by panchi64** [comment]
Any progress so far? Anything I can help with?

**Comment by panchi64** [comment]
Just noticed the pull request connected to the issue, I'll check it as soon as I get the chance. (Hopefully today)

**Comment by panchi64** [comment]
Should this be moved to "In Review" as well?
