### ISSUE TITLE
Combine components to build the services page

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#43]
This would be the final part of the UI. It involves placing all of the components that have been previously created together to form a cohesive experience for the user.

Task worth: 48pts (6pts from high priority * 8pts from intermediate difficulty)

**Comment by panchi64** [comment]
Any updates on this? 

If you haven't started, from what I understand all of the components needed for the page are ready. It would just take a merge of those branches in your computer to combining/using them

**Comment by panchi64** [comment]
Just following up on any progress.

**Comment by gustavosotero** [comment]
I have a rendering mockup version of the page, currently adding functionality to the search bar component.

**Comment by Yahid1** [comment]
I think this task is done

**Comment by Yahid1** [comment]
You can review it

**Comment by panchi64** [comment]
> You can review it
Move this task to "In Review" if its done and awaiting a review pls

**Comment by Yahid1** [comment]
Done
