### ISSUE TITLE
Team 1 - Design Home page

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#5]
Pair with another dev create a simple wireframe/mock-up of the home page. 

- The home page includes Login and sign up
- An area for the courses where the student is actively taking tutoring.
- An area for the courses that the student is taking that same semester. 

You can add more ideas or take out ideas

**Comment by PinkSylvie** [comment]
**[Team 1 Figma - Home UI Design](https://www.figma.com/file/FENYnjfiNHmKVJDi5UGaGm/TEAM-1---UI-Design-Draft?type=design&node-id=0-1&mode=design&t=X1Q7hiqxe1kySJnK-0)** 
Team 1's Design is ready for review @print-Eruki 

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/93553908/9983a280-cddb-4879-a97b-2455acf1c870)

**Comment by print-Eruki** [comment]
I love the design! Great job!

**Comment by PinkSylvie** [comment]
Completed
