### ISSUE TITLE
Team 3 - Tutoring Detail Page

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#52]
- This page would be for when you have an upcoming session with a tutor, allowing you to see everything in more detail.
- Reservation Details
   - Entry and exit time
- Meet link
- Cancellation option
Task Worth: 48 pts (6pts from high priority * 8pts form Advance difficulty)

**Comment by Jvstinoo** [comment]
I have published the branch with this feature. Creates an Upcoming Session view showing the next session's details.

![IMG_9931](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72774910/57dce43f-452e-4c43-a1c3-57f9be647cf2)
