### ISSUE TITLE
Refactoring "handleSearch function" to edge cases

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#69]
Fix the Search filter from the Search bar component

**Comment by Jonathan-Rod** [comment]
Refactored `handleSearch` function for the following edge cases:
 - [x] Rendering components for none text input 
 - [x] Rendering components for spaces text input
 - [x] Filtering to match department name 
 - [x] Filtering to match course name 
 - [x] Filtering to match tutor name 
 - [ ] Rendering 'Not Found' if empty search result list

**Comment by panchi64** [comment]
The rendering not found if empty will be created into a separate task and given to @williammartinez10
