### ISSUE TITLE
Team 1 - Design Activity page

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#7]
Create wireframes/mockups of the activity page which may or not include:

- Activities 
   - Chats
   - Notifications

Task points: 2 (Difficulty) * 6 (Priority) = 12 pts

**Comment by sandy-marrero** [comment]
https://www.figma.com/file/7rpnGc5pb4MTCMMrOzQvAa/Service-Page-Team-1?type=design&node-id=1%3A4071&mode=design&t=sRoR2ck8BbFTBULq-1
