### ISSUE TITLE
TEAM 1 - Documentation Milestone 1

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#70]
This task involved documenting all the work the team 1 has made in milestone 1, as well as meeting with other developers from the other teams to document all the work concurrently from all the teams.

Task points: 4 (Dificulty) * 7 (Priority) = 28 pts

**Comment by PinkSylvie** [comment]
[Milestone Documentation Google Doc](https://docs.google.com/document/d/1BFH-jMxeQUkulSXozFVO41hrATL9jMLq3H0X-UzbsDk/edit?usp=sharing)
Is ready for review! The missing information will be added by managers. @print-Eruki
