### ISSUE TITLE
TEAM 1 - Create base components for Tutor view in Profile Page 

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#72]
The task involves creating the base of the components that are going to be needed for the profile page. Only create the base no implementation

This components might be:

Ratings component
Classes component
contact-info component

etc

Use the designs made to determine which components are going to be needed

Task points: 4 (Difficulty) * 6 (Priority) = 24 pts

**Comment by Kiam11** [comment]
https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/tree/Tutor-Base-Components
