### ISSUE TITLE
Search Page Bug Fix

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#73]
### Discussed in https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **panchi64** September 18, 2023</sup>
Alrighty drop the convo here team 2.
@Jonathan-Rod @williammartinez10 @gustavosotero @RicardoJRSs @Yahid1 @yahirfigueroa y everyone else I can't remember rn</div>

Bug In the Search function. Read discussion for better insight!!

**Comment by Jonathan-Rod** [comment]
I commit and push to serv_page branch a refactored and cleaned up version of service page and search bar
