### ISSUE TITLE
TEAM 1 - Implementation of profile picture (user) component

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#77]
Implement the profile picture component for the user view. For now this component should receive as a parameter a path to an existing picture in the project, to load it and show it in the profile page.

Task points: 4 (Difficulty) * 5 (Priority) = 20 pts

**Comment by jacorderopr** [comment]
The feature has been implemented and pushed to a beach called profilePictureComponent. Said component is currently being used in the mock profile picture in said branch.

**Comment by print-Eruki** [comment]
Nice job! Looks great @jacorderopr! 

I will award you 8pts for going the extra mile on this task.
