### ISSUE TITLE
TEAM 1 - Implementation of profile picture (tutor) component

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#78]
Implement the profile picture component for the TUTOR view. Overload the profile picture component from the user to create one unique for the tutor. This means do not create a new component reuse the one for the user.

Task points: 4 (Difficulty) * 6 (Priority) = 24 pts

**Comment by jorge-torres33** [comment]
https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/tree/Team1-ProfilePic-Component-Implementation
