### ISSUE TITLE
TEAM 1 - Implementation of description/bio component

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#79]
This talks revolves around implementing the description or biography component. This component displays a short message about the student/tutor. 

Task Points: 5 (Difficulty) * 5 (Priority) = 20 pts

**Comment by jorge-torres33** [comment]
https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/tree/team1-description-bio-mockup
