### ISSUE TITLE
Create a UI element to notify the user there are no search results

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#81]
As requested by a previous task and some team members. It would be a good idea to have a visual representation of the search engine not finding any results. This tasks encapsulates just that. Create a UI component that is rendered when the search bar returns no results.

Task worth: 16pts (4pts from a medium priority * 4pts from an intermediate difficulty)

**Comment by panchi64** [comment]
Could you post a picture or video of the component here showing up appropriately here?

**Comment by williammartinez10** [comment]
https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/77518982/7d354f8b-9bc9-4cea-b42c-40b950864f5a
