### ISSUE TITLE
Team 3 - Previous Courses Component 

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#85]
- Create a component that receives information about previous courses and generates a clickable card.
    - When you click on this card, it will take you to the "Tutoring Detail Page."

Task Worth: 34pts (6pts from high priority * 4pts form intermediate difficulty + 10 pts  bonus)

**Comment by Techno857** [comment]
Implementation has been completed.
