### ISSUE TITLE
TEAM 4 - Database documentation 

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#87]
This task will be to create basic documentation about the database so far, this will include how to access it, how to traverse it, and a brief explanation of the tech stack and how it shall operate. This WILL not have to be the final documentation nor the submission for Milestone 1, but it may facilitate the understanding of the database and other people's work. 

Task Worth: 32pts (4pts Intermediate * 8pts Urgent Urgency)

**Comment by KVA27** [comment]
https://docs.google.com/document/d/1RKNEWqUE3i8QQP3MmbBVGK72tX5d6WuBZp_fo9-Nrqo/edit?usp=sharing

**Comment by OrdepA17** [comment]
Good work! Points have been awarded
