### ISSUE TITLE
TEAM 4 - Database query creation for Users

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#88]
You will work on different query creation during this sprint. The essence of this task is to create different queries regarding the Users profile page and user table. This shall range from basic get all users to more specific searches like finding tutors for a specific class. Since the issue has been readjusted on short notice, query variation will be simple. For this sprint, it is important to be able to find users via their unique IDs, names, last names, emails, and if they are a tutor. Bonus points if a query that finds users based on a given class is created. EX: Find all the students who are taking the INSO 101 class and it returns all of them.

To submit this task, you may create a basic file that contains all the queries and pictures of your results. When API configurations and live testing are enabled these queries will be retested in the new environment.
Feel free to add any resources found that may facilitate the work of the tasks in the comments, as well as any ideas or discussions regarding the database. 

Task worth: 48 pts (8pts from Urgent priority + 6pts from hard difficulty) (Note if two people participate in the task points will be split)

Here is an sql cheat sheet to help with its creation.
https://intellipaat.com/blog/tutorial/sql-tutorial/sql-commands-cheat-sheet/

**Comment by firecharge0** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/4e4b6982-2b92-42c4-8440-9e5c29de5e8e)

![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/3af66e22-9371-4666-8d21-ce9398c3223b)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/f6c66b08-0d22-443c-bb11-ef8b43f657db)'
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/52acce77-4d2c-4abe-8cc1-89fe7160893c)
![image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/49455042/40aeaa13-7b18-4337-89df-00f45bedcfd3)
Here are the queries for searching for a student by id, name as well as a a query that returns the list of tutors.
The first image is the base query that the other queries filter from.

**Comment by dylanDeJesus21** [comment]
![byLastName](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/33931071-f91f-46e3-987e-31907eecece6)
![ResultByBName](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/652f05c7-3507-471a-af45-bb45f1047d6f)
Query by last name

![ByEmail](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/2446b58b-a4e1-4fac-bfec-ad18edc64635)
![resultsByEmail](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/f670b635-9440-4b60-83ba-88d0bb01bb3d)
Query for searching by email

![ByActiveCourse](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/8509fbf5-14d6-45fd-bf04-81e90747c217)
![resultsByCourse](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/98779392/a75255f5-f1c4-4d15-94c9-9152c1790b46)

This would be the query for a specific active course. 

In these queries we are only selecting the names, last_name, email, and active course columns.'

**Comment by OrdepA17** [comment]
Great work, 6 points from bonus task and extra querries. 3 points awarded to each developer.
