### ISSUE TITLE
TEAM 4 - Database query creation for Courses

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#89]
You will work on different query creation during this sprint. The essence of this task is to create different queries regarding the Services page and courses table. This shall range from basic get-all courses to more specific searches like finding courses given by a specific tutor. Since the issue has been readjusted on short notice, query variation will be simple. For this sprint, it is important to be able to find courses via their unique IDs, Course names, and courses given by a specific tutor. Bonus points if a query that finds classes taken by a student based on a given name or ID is created. EX: Find all the classes that student X is taking and it returns all of the classes. This shall be an initial guide since the relationship between the courses, the students, and the tutors is still under development and has to be flushed out more.

To submit this task, you may create a basic file that contains all the queries and pictures of your results. When API configurations and live testing are enabled these queries will be retested in the new environment.
Feel free to add any resources found that may facilitate the work of the tasks in the comments, as well as any ideas or discussions regarding the database.

Task worth: 48 pts (8pts from high priority + 6pts from hard difficulty) (Note if two people participate in the task points will be split)

Here is an sql cheat sheet to help with its creation.
https://intellipaat.com/blog/tutorial/sql-tutorial/sql-commands-cheat-sheet/

**Comment by JadiellMV** [comment]
Daniel Febles and I completed this task!

**Comment by DanielFebles** [comment]
Can corroborate.

**Comment by OrdepA17** [comment]
Good work! Points have been awarded.
