### ISSUE TITLE
Design Home page style using Figma

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#9]
Assignees will be tasked with creating a draft of how they think the corresponding page should look like

**Comment by OrdepA17** [comment]
The home page will contain a small icon that will lead to the user's profile, it will also contain an area where the user can access their 3-5 most recent courses as well as see more course suggestions below it. A Sign Up/Log in button can substitute the users icon if they have not logged in or if there is a new user

**Comment by KVA27** [comment]
![IMG_0404](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/90231140/ee546c37-d5dc-4108-851e-1dac89fceb91)

**Comment by OrdepA17** [comment]
Designs have been approved and are under final selection with the designs from the other teams. 
Priority Low = 2 Points
Difficulty Low = 2 Points
Modifier = 4 Points (for team collaboration)

Total: 4 Points Awarded for each developer
