### ISSUE TITLE
TEAM 1 - Create video of what team 1 achieve in milestone 1

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#94]
Create a video where you discuss what team 1 has achieved for this milestone, this will include the tasks and all the development in the profile page. You will need to provide a video demoing the profile page or documentation that was done. Any questions please feel free to contact me.

Task points: 4 (Difficulty) * 6 (Priority)  = 24 pts

**Comment by Kiam11** [comment]
https://sistemaupr-my.sharepoint.com/:v:/g/personal/kiam_perez_upr_edu/EWIc9i2Wj5BJnRKGznh0iQwBzkgTT9IY9WjgFW-_K3UGSA
