### ISSUE TITLE
TEAM 4 - User Query Documentation

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#99]
Document all queries created from Issue #88 in to the Database Documentation from Issue #87.
Attach results, query and a brief explanation into the documentation. Comment under this issue when task has been completed.

Task Worth: 20pts (10 pts Deadline is tomorrow!!! priority * 2pts Easy difficulty)

**Comment by firecharge0** [comment]
I have finished documenting function the functions queries to return all users, users by id, user by name as well as a function query to return all users registered as tutors.

**Comment by dylanDeJesus21** [comment]
Finished documenting the user queries to return users by last_name, email, and by specific active courses.

**Comment by OrdepA17** [comment]
Good work! Points have been updated.
